// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 1; // obj_flicky_logo
global.__objectDepths[1] = 0; // obj_flicky_setup
global.__objectDepths[2] = 0; // obj_flicky_plane
global.__objectDepths[3] = 0; // obj_flicky_credits
global.__objectDepths[4] = 0; // par_controller
global.__objectDepths[5] = -10000; // obj_camera
global.__objectDepths[6] = 0; // obj_audio_manager
global.__objectDepths[7] = -999997; // obj_level_controller
global.__objectDepths[8] = 0; // obj_global_manager
global.__objectDepths[9] = -999998; // obj_title_card_controller
global.__objectDepths[10] = -999998; // obj_game_over
global.__objectDepths[11] = -999998; // obj_pause_menu
global.__objectDepths[12] = -1; // obj_insta_shield
global.__objectDepths[13] = -1; // obj_hammerdrop_hitbox
global.__objectDepths[14] = 0; // par_character
global.__objectDepths[15] = 0; // par_collision_terrain
global.__objectDepths[16] = 0; // par_collision_solid
global.__objectDepths[17] = 0; // par_collision_solid_no_angle
global.__objectDepths[18] = 0; // par_collision_platform
global.__objectDepths[19] = 0; // par_collision_platform_no_angle
global.__objectDepths[20] = 0; // par_collision_obstacles
global.__objectDepths[21] = 0; // par_collision_layer_low
global.__objectDepths[22] = 0; // par_collision_layer_high
global.__objectDepths[23] = 0; // par_collision_collapse
global.__objectDepths[24] = 0; // par_collision_collapse_tiles
global.__objectDepths[25] = 0; // par_collision_pushable
global.__objectDepths[26] = 0; // par_collision_moving
global.__objectDepths[27] = 10; // par_collision_swing
global.__objectDepths[28] = 0; // obj_sensor_layer_low
global.__objectDepths[29] = 0; // obj_sensor_layer_high
global.__objectDepths[30] = 0; // obj_sensor_layer_switch
global.__objectDepths[31] = 0; // obj_sensor_lock_tunnel_right
global.__objectDepths[32] = 0; // obj_sensor_lock_tunnel_left
global.__objectDepths[33] = 0; // par_collision_launch_sensor
global.__objectDepths[34] = -100000000; // obj_collision_launch_sensor_right
global.__objectDepths[35] = -100000000; // obj_collision_launch_sensor_left
global.__objectDepths[36] = 1; // obj_ring
global.__objectDepths[37] = 1; // obj_starpost
global.__objectDepths[38] = 0; // par_spring
global.__objectDepths[39] = 0; // par_spring_diagonal
global.__objectDepths[40] = 0; // obj_spring_up
global.__objectDepths[41] = 0; // obj_spring_down
global.__objectDepths[42] = 0; // obj_spring_left
global.__objectDepths[43] = 0; // obj_spring_right
global.__objectDepths[44] = 0; // obj_spring_diagonal_right
global.__objectDepths[45] = 0; // obj_spring_diagonal_left
global.__objectDepths[46] = 0; // obj_spring_diagonal_d_right
global.__objectDepths[47] = 0; // obj_spring_diagonal_d_left
global.__objectDepths[48] = 0; // obj_spring_up_red
global.__objectDepths[49] = 0; // obj_spring_down_red
global.__objectDepths[50] = 0; // obj_spring_left_red
global.__objectDepths[51] = 0; // obj_spring_right_red
global.__objectDepths[52] = 0; // obj_shield_flame
global.__objectDepths[53] = 0; // obj_shield_electricity
global.__objectDepths[54] = 0; // obj_shield_bubble
global.__objectDepths[55] = 0; // obj_monitor
global.__objectDepths[56] = 1; // obj_monitor_destroyed
global.__objectDepths[57] = 0; // obj_monitor_rings
global.__objectDepths[58] = 0; // obj_monitor_life
global.__objectDepths[59] = 0; // obj_monitor_bubble_shield
global.__objectDepths[60] = 0; // obj_monitor_flame_shield
global.__objectDepths[61] = 0; // obj_monitor_electricity_shield
global.__objectDepths[62] = 0; // obj_monitor_invincibility
global.__objectDepths[63] = 0; // obj_monitor_speedshoe
global.__objectDepths[64] = 1; // obj_sign_post
global.__objectDepths[65] = -999995; // obj_scoring_results
global.__objectDepths[66] = 0; // obj_sign_post_camera
global.__objectDepths[67] = 3; // obj_animal_flicky
global.__objectDepths[68] = 3; // obj_animal_cucky
global.__objectDepths[69] = 3; // obj_animal_ricky
global.__objectDepths[70] = 3; // obj_animal_rocky
global.__objectDepths[71] = 3; // obj_animal_pecky
global.__objectDepths[72] = 3; // obj_animal_pocky
global.__objectDepths[73] = 0; // par_enemy
global.__objectDepths[74] = 0; // par_harmful
global.__objectDepths[75] = 0; // par_harmful_fire
global.__objectDepths[76] = 0; // par_boss
global.__objectDepths[77] = 0; // obj_npc_sth1_motobug
global.__objectDepths[78] = 0; // obj_npc_sth1_splats
global.__objectDepths[79] = -10; // obj_npc_sth1_chopper
global.__objectDepths[80] = -100; // obj_npc_sth2_asteron
global.__objectDepths[81] = -100; // obj_npc_sth2_asteron_spike
global.__objectDepths[82] = 0; // obj_npc_sth3_bloominator
global.__objectDepths[83] = 0; // obj_npc_sth3_jawz
global.__objectDepths[84] = 0; // obj_npc_sth3_bloominator_spike
global.__objectDepths[85] = 0; // obj_badnik_wall
global.__objectDepths[86] = 1; // obj_npc_sth3_knuckles
global.__objectDepths[87] = 1; // obj_npc_sth3_firebreather
global.__objectDepths[88] = 0; // obj_npc_sth3_firebreather_flame
global.__objectDepths[89] = 0; // obj_npc_sth3_firebreather_projectile
global.__objectDepths[90] = 0; // obj_npc_sth3_firebreather_parts
global.__objectDepths[91] = 0; // obj_boss_camera
global.__objectDepths[92] = -5; // obj_lava_surface
global.__objectDepths[93] = 4; // obj_lava_fall
global.__objectDepths[94] = 0; // par_spike
global.__objectDepths[95] = 0; // obj_spike_up
global.__objectDepths[96] = 0; // obj_spike_down
global.__objectDepths[97] = 0; // obj_spike_left
global.__objectDepths[98] = 0; // obj_spike_right
global.__objectDepths[99] = -1; // obj_bonus_spark
global.__objectDepths[100] = 0; // obj_sensor_pixel
global.__objectDepths[101] = 0; // obj_sensor_line
global.__objectDepths[102] = 0; // obj_effect_dummy
global.__objectDepths[103] = -5; // obj_effect_score
global.__objectDepths[104] = -10; // obj_amy_heart
global.__objectDepths[105] = -10; // obj_hammerdrop_dust
global.__objectDepths[106] = -1; // obj_skid_dust
global.__objectDepths[107] = 0; // obj_invincibility_sparkle
global.__objectDepths[108] = 0; // obj_hyper_sparkle
global.__objectDepths[109] = 0; // obj_aftereffect
global.__objectDepths[110] = 0; // obj_electricity_spark
global.__objectDepths[111] = -999999; // obj_effect_screenflash
global.__objectDepths[112] = -999999; // obj_effect_electro_flash
global.__objectDepths[113] = 0; // obj_null
global.__objectDepths[114] = 0; // obj_chemical_dasher
global.__objectDepths[115] = 0; // par_bridge
global.__objectDepths[116] = 0; // obj_aaz_bridge
global.__objectDepths[117] = -999996; // obj_water
global.__objectDepths[118] = 1; // obj_bubble_generator
global.__objectDepths[119] = -10000; // obj_air_bubble
global.__objectDepths[120] = 0; // obj_water_countdown
global.__objectDepths[121] = 1; // obj_casino_bumper
global.__objectDepths[122] = 0; // obj_moving_handle_up
global.__objectDepths[123] = 0; // obj_moving_handle_down
global.__objectDepths[124] = 0; // obj_moving_handle_right
global.__objectDepths[125] = 0; // obj_moving_handle_left
global.__objectDepths[126] = 10; // obj_marble_swing
global.__objectDepths[127] = 0; // obj_dialogue_box
global.__objectDepths[128] = 0; // par_hang
global.__objectDepths[129] = 0; // obj_hang_test
global.__objectDepths[130] = 0; // obj_sth3_switch
global.__objectDepths[131] = 0; // obj_chaos_emeralds
global.__objectDepths[132] = 0; // obj_zne_test_1
global.__objectDepths[133] = 0; // obj_zne_test_1_pla
global.__objectDepths[134] = 0; // obj_zne_test_2
global.__objectDepths[135] = 0; // obj_zne_test_3
global.__objectDepths[136] = 0; // obj_zne_test_4
global.__objectDepths[137] = 0; // obj_zne_test_5
global.__objectDepths[138] = 0; // obj_zne_test_6
global.__objectDepths[139] = 0; // obj_zne_test_7
global.__objectDepths[140] = 0; // obj_zne_test_8
global.__objectDepths[141] = 0; // obj_zne_test_9
global.__objectDepths[142] = 0; // obj_zne_test_10
global.__objectDepths[143] = 0; // obj_zne_test_11
global.__objectDepths[144] = 0; // obj_zne_test_12
global.__objectDepths[145] = 0; // obj_zne_test_13
global.__objectDepths[146] = 0; // obj_zne_test_14
global.__objectDepths[147] = 0; // obj_zne_test_15
global.__objectDepths[148] = 0; // obj_zne_test_16
global.__objectDepths[149] = 0; // obj_zne_test_17
global.__objectDepths[150] = 0; // obj_zne_test_18
global.__objectDepths[151] = 1; // obj_zne_test_loop_high
global.__objectDepths[152] = 5; // obj_zne_test_loop_solid
global.__objectDepths[153] = -10; // obj_zne_test_loop_low
global.__objectDepths[154] = -1; // obj_zne_test_tunnel
global.__objectDepths[155] = 1; // obj_zne_test_moving_platform
global.__objectDepths[156] = 1; // obj_zne_test_moving_creator
global.__objectDepths[157] = -99999; // obj_zne_test_debug
global.__objectDepths[158] = 0; // obj_zne_test_settime
global.__objectDepths[159] = 0; // obj_zne_test_collapse
global.__objectDepths[160] = 0; // obj_zne_test_collapse_pieces
global.__objectDepths[161] = 0; // obj_sky_collapse
global.__objectDepths[162] = 0; // obj_sky_collapse_pieces
global.__objectDepths[163] = 99999999; // objGHZBG
global.__objectDepths[164] = 7; // obj_bonus_gumball_machine
global.__objectDepths[165] = 0; // obj_bonus_gumball_tiles
global.__objectDepths[166] = 3; // obj_bonus_gumball_rod
global.__objectDepths[167] = 4; // obj_bonus_gumball_plate
global.__objectDepths[168] = -1; // obj_bonus_gumball_bumper
global.__objectDepths[169] = 0; // obj_bonus_gumball_collapse
global.__objectDepths[170] = 0; // obj_bonus_gumball_collapse_pieces
global.__objectDepths[171] = 0; // obj_bonus_gumball_spring_breaker
global.__objectDepths[172] = 9999999; // obj_bonus_gumball_background
global.__objectDepths[173] = 5; // obj_bonus_gumball
global.__objectDepths[174] = -999999; // par_fade
global.__objectDepths[175] = -999999; // obj_fade_next
global.__objectDepths[176] = -999999; // obj_fade_bonus
global.__objectDepths[177] = -999999; // obj_fade_from_bonus
global.__objectDepths[178] = -999999; // obj_fade_restart
global.__objectDepths[179] = -999999; // obj_fade_game_restart
global.__objectDepths[180] = -999999; // obj_fade_end
global.__objectDepths[181] = -999999; // obj_fade_super
global.__objectDepths[182] = -999999; // obj_fade_to_normal
global.__objectDepths[183] = -10240; // obj_collision_terrain01
global.__objectDepths[184] = -10240; // obj_collision_terrain02
global.__objectDepths[185] = -10240; // obj_collision_terrain03
global.__objectDepths[186] = -10240; // obj_collision_terrain04
global.__objectDepths[187] = -10240; // obj_collision_terrain05
global.__objectDepths[188] = -10240; // obj_collision_terrain06
global.__objectDepths[189] = -10240; // obj_collision_terrain07
global.__objectDepths[190] = -10240; // obj_collision_terrain08
global.__objectDepths[191] = -10240; // obj_collision_terrain09
global.__objectDepths[192] = -10240; // obj_collision_terrain10
global.__objectDepths[193] = -10240; // obj_collision_terrain11
global.__objectDepths[194] = -10240; // obj_collision_terrain12
global.__objectDepths[195] = -10240; // obj_collision_terrain13
global.__objectDepths[196] = -10240; // obj_collision_terrain14
global.__objectDepths[197] = -10240; // obj_collision_terrain15
global.__objectDepths[198] = -10240; // obj_collision_terrain16
global.__objectDepths[199] = -10240; // obj_collision_terrain17
global.__objectDepths[200] = -10240; // obj_collision_terrain18
global.__objectDepths[201] = -10240; // obj_collision_terrain19
global.__objectDepths[202] = -10240; // obj_collision_terrain20
global.__objectDepths[203] = -10240; // obj_collision_terrain21
global.__objectDepths[204] = -10240; // obj_collision_terrain22
global.__objectDepths[205] = -10240; // obj_collision_terrain23
global.__objectDepths[206] = -10240; // obj_collision_terrain_layer_0_01
global.__objectDepths[207] = -10240; // obj_collision_terrain_layer_0_02
global.__objectDepths[208] = -10240; // obj_collision_terrain_layer_0_03
global.__objectDepths[209] = -10240; // obj_collision_terrain_layer_0_04
global.__objectDepths[210] = -10240; // obj_collision_terrain_layer_0_05
global.__objectDepths[211] = -10240; // obj_collision_terrain_layer_0_06
global.__objectDepths[212] = -10240; // obj_collision_terrain_layer_0_07
global.__objectDepths[213] = -10240; // obj_collision_terrain_layer_0_08
global.__objectDepths[214] = -10240; // obj_collision_terrain_layer_0_09
global.__objectDepths[215] = -10240; // obj_collision_terrain_layer_0_10
global.__objectDepths[216] = -10240; // obj_collision_terrain_layer_0_11
global.__objectDepths[217] = -10240; // obj_collision_terrain_layer_0_12
global.__objectDepths[218] = -10240; // obj_collision_terrain_layer_0_13
global.__objectDepths[219] = -10240; // obj_collision_terrain_layer_0_14
global.__objectDepths[220] = -10240; // obj_collision_terrain_layer_0_15
global.__objectDepths[221] = -10240; // obj_collision_terrain_layer_0_16
global.__objectDepths[222] = -10240; // obj_collision_terrain_layer_0_17
global.__objectDepths[223] = -10240; // obj_collision_terrain_layer_0_18
global.__objectDepths[224] = -10240; // obj_collision_terrain_layer_0_19
global.__objectDepths[225] = -10240; // obj_collision_terrain_layer_0_20
global.__objectDepths[226] = -10240; // obj_collision_terrain_layer_0_21
global.__objectDepths[227] = -10240; // obj_collision_terrain_layer_0_22
global.__objectDepths[228] = -10240; // obj_collision_terrain_layer_0_23
global.__objectDepths[229] = -10240; // obj_collision_terrain_layer_1_01
global.__objectDepths[230] = -10240; // obj_collision_terrain_layer_1_02
global.__objectDepths[231] = -10240; // obj_collision_terrain_layer_1_03
global.__objectDepths[232] = -10240; // obj_collision_terrain_layer_1_04
global.__objectDepths[233] = -10240; // obj_collision_terrain_layer_1_05
global.__objectDepths[234] = -10240; // obj_collision_terrain_layer_1_06
global.__objectDepths[235] = -10240; // obj_collision_terrain_layer_1_07
global.__objectDepths[236] = -10240; // obj_collision_terrain_layer_1_08
global.__objectDepths[237] = -10240; // obj_collision_terrain_layer_1_09
global.__objectDepths[238] = -10240; // obj_collision_terrain_layer_1_10
global.__objectDepths[239] = -10240; // obj_collision_terrain_layer_1_11
global.__objectDepths[240] = -10240; // obj_collision_terrain_layer_1_12
global.__objectDepths[241] = -10240; // obj_collision_terrain_layer_1_13
global.__objectDepths[242] = -10240; // obj_collision_terrain_layer_1_14
global.__objectDepths[243] = -10240; // obj_collision_terrain_layer_1_15
global.__objectDepths[244] = -10240; // obj_collision_terrain_layer_1_16
global.__objectDepths[245] = -10240; // obj_collision_terrain_layer_1_17
global.__objectDepths[246] = -10240; // obj_collision_terrain_layer_1_18
global.__objectDepths[247] = -10240; // obj_collision_terrain_layer_1_19
global.__objectDepths[248] = -10240; // obj_collision_terrain_layer_1_20
global.__objectDepths[249] = -10240; // obj_collision_terrain_layer_1_21
global.__objectDepths[250] = -10240; // obj_collision_terrain_layer_1_22
global.__objectDepths[251] = -10240; // obj_collision_terrain_layer_1_23
global.__objectDepths[252] = -10240; // obj_collision_terrain_platform_01
global.__objectDepths[253] = -10240; // obj_collision_terrain_platform_02
global.__objectDepths[254] = -10240; // obj_collision_terrain_platform_03
global.__objectDepths[255] = -10240; // obj_collision_terrain_platform_04
global.__objectDepths[256] = -10240; // obj_collision_terrain_platform_05
global.__objectDepths[257] = -10240; // obj_collision_terrain_platform_06
global.__objectDepths[258] = -10240; // obj_collision_terrain_platform_07
global.__objectDepths[259] = -10240; // obj_collision_terrain_platform_08
global.__objectDepths[260] = -10240; // obj_collision_terrain_platform_09
global.__objectDepths[261] = -10240; // obj_collision_terrain_platform_10
global.__objectDepths[262] = -10240; // obj_collision_terrain_platform_11
global.__objectDepths[263] = -10240; // obj_collision_terrain_platform_12
global.__objectDepths[264] = -10240; // obj_collision_terrain_platform_13
global.__objectDepths[265] = -10240; // obj_collision_terrain_platform_14
global.__objectDepths[266] = -10240; // obj_collision_terrain_platform_15
global.__objectDepths[267] = -10240; // obj_collision_terrain_platform_16
global.__objectDepths[268] = -10240; // obj_collision_terrain_platform_17
global.__objectDepths[269] = -10240; // obj_collision_terrain_platform_18
global.__objectDepths[270] = -10240; // obj_collision_terrain_platform_19
global.__objectDepths[271] = -10240; // obj_collision_terrain_platform_20
global.__objectDepths[272] = -10240; // obj_collision_terrain_platform_21
global.__objectDepths[273] = -10240; // obj_collision_terrain_platform_22
global.__objectDepths[274] = -10240; // obj_collision_terrain_platform_23


global.__objectNames[0] = "obj_flicky_logo";
global.__objectNames[1] = "obj_flicky_setup";
global.__objectNames[2] = "obj_flicky_plane";
global.__objectNames[3] = "obj_flicky_credits";
global.__objectNames[4] = "par_controller";
global.__objectNames[5] = "obj_camera";
global.__objectNames[6] = "obj_audio_manager";
global.__objectNames[7] = "obj_level_controller";
global.__objectNames[8] = "obj_global_manager";
global.__objectNames[9] = "obj_title_card_controller";
global.__objectNames[10] = "obj_game_over";
global.__objectNames[11] = "obj_pause_menu";
global.__objectNames[12] = "obj_insta_shield";
global.__objectNames[13] = "obj_hammerdrop_hitbox";
global.__objectNames[14] = "par_character";
global.__objectNames[15] = "par_collision_terrain";
global.__objectNames[16] = "par_collision_solid";
global.__objectNames[17] = "par_collision_solid_no_angle";
global.__objectNames[18] = "par_collision_platform";
global.__objectNames[19] = "par_collision_platform_no_angle";
global.__objectNames[20] = "par_collision_obstacles";
global.__objectNames[21] = "par_collision_layer_low";
global.__objectNames[22] = "par_collision_layer_high";
global.__objectNames[23] = "par_collision_collapse";
global.__objectNames[24] = "par_collision_collapse_tiles";
global.__objectNames[25] = "par_collision_pushable";
global.__objectNames[26] = "par_collision_moving";
global.__objectNames[27] = "par_collision_swing";
global.__objectNames[28] = "obj_sensor_layer_low";
global.__objectNames[29] = "obj_sensor_layer_high";
global.__objectNames[30] = "obj_sensor_layer_switch";
global.__objectNames[31] = "obj_sensor_lock_tunnel_right";
global.__objectNames[32] = "obj_sensor_lock_tunnel_left";
global.__objectNames[33] = "par_collision_launch_sensor";
global.__objectNames[34] = "obj_collision_launch_sensor_right";
global.__objectNames[35] = "obj_collision_launch_sensor_left";
global.__objectNames[36] = "obj_ring";
global.__objectNames[37] = "obj_starpost";
global.__objectNames[38] = "par_spring";
global.__objectNames[39] = "par_spring_diagonal";
global.__objectNames[40] = "obj_spring_up";
global.__objectNames[41] = "obj_spring_down";
global.__objectNames[42] = "obj_spring_left";
global.__objectNames[43] = "obj_spring_right";
global.__objectNames[44] = "obj_spring_diagonal_right";
global.__objectNames[45] = "obj_spring_diagonal_left";
global.__objectNames[46] = "obj_spring_diagonal_d_right";
global.__objectNames[47] = "obj_spring_diagonal_d_left";
global.__objectNames[48] = "obj_spring_up_red";
global.__objectNames[49] = "obj_spring_down_red";
global.__objectNames[50] = "obj_spring_left_red";
global.__objectNames[51] = "obj_spring_right_red";
global.__objectNames[52] = "obj_shield_flame";
global.__objectNames[53] = "obj_shield_electricity";
global.__objectNames[54] = "obj_shield_bubble";
global.__objectNames[55] = "obj_monitor";
global.__objectNames[56] = "obj_monitor_destroyed";
global.__objectNames[57] = "obj_monitor_rings";
global.__objectNames[58] = "obj_monitor_life";
global.__objectNames[59] = "obj_monitor_bubble_shield";
global.__objectNames[60] = "obj_monitor_flame_shield";
global.__objectNames[61] = "obj_monitor_electricity_shield";
global.__objectNames[62] = "obj_monitor_invincibility";
global.__objectNames[63] = "obj_monitor_speedshoe";
global.__objectNames[64] = "obj_sign_post";
global.__objectNames[65] = "obj_scoring_results";
global.__objectNames[66] = "obj_sign_post_camera";
global.__objectNames[67] = "obj_animal_flicky";
global.__objectNames[68] = "obj_animal_cucky";
global.__objectNames[69] = "obj_animal_ricky";
global.__objectNames[70] = "obj_animal_rocky";
global.__objectNames[71] = "obj_animal_pecky";
global.__objectNames[72] = "obj_animal_pocky";
global.__objectNames[73] = "par_enemy";
global.__objectNames[74] = "par_harmful";
global.__objectNames[75] = "par_harmful_fire";
global.__objectNames[76] = "par_boss";
global.__objectNames[77] = "obj_npc_sth1_motobug";
global.__objectNames[78] = "obj_npc_sth1_splats";
global.__objectNames[79] = "obj_npc_sth1_chopper";
global.__objectNames[80] = "obj_npc_sth2_asteron";
global.__objectNames[81] = "obj_npc_sth2_asteron_spike";
global.__objectNames[82] = "obj_npc_sth3_bloominator";
global.__objectNames[83] = "obj_npc_sth3_jawz";
global.__objectNames[84] = "obj_npc_sth3_bloominator_spike";
global.__objectNames[85] = "obj_badnik_wall";
global.__objectNames[86] = "obj_npc_sth3_knuckles";
global.__objectNames[87] = "obj_npc_sth3_firebreather";
global.__objectNames[88] = "obj_npc_sth3_firebreather_flame";
global.__objectNames[89] = "obj_npc_sth3_firebreather_projectile";
global.__objectNames[90] = "obj_npc_sth3_firebreather_parts";
global.__objectNames[91] = "obj_boss_camera";
global.__objectNames[92] = "obj_lava_surface";
global.__objectNames[93] = "obj_lava_fall";
global.__objectNames[94] = "par_spike";
global.__objectNames[95] = "obj_spike_up";
global.__objectNames[96] = "obj_spike_down";
global.__objectNames[97] = "obj_spike_left";
global.__objectNames[98] = "obj_spike_right";
global.__objectNames[99] = "obj_bonus_spark";
global.__objectNames[100] = "obj_sensor_pixel";
global.__objectNames[101] = "obj_sensor_line";
global.__objectNames[102] = "obj_effect_dummy";
global.__objectNames[103] = "obj_effect_score";
global.__objectNames[104] = "obj_amy_heart";
global.__objectNames[105] = "obj_hammerdrop_dust";
global.__objectNames[106] = "obj_skid_dust";
global.__objectNames[107] = "obj_invincibility_sparkle";
global.__objectNames[108] = "obj_hyper_sparkle";
global.__objectNames[109] = "obj_aftereffect";
global.__objectNames[110] = "obj_electricity_spark";
global.__objectNames[111] = "obj_effect_screenflash";
global.__objectNames[112] = "obj_effect_electro_flash";
global.__objectNames[113] = "obj_null";
global.__objectNames[114] = "obj_chemical_dasher";
global.__objectNames[115] = "par_bridge";
global.__objectNames[116] = "obj_aaz_bridge";
global.__objectNames[117] = "obj_water";
global.__objectNames[118] = "obj_bubble_generator";
global.__objectNames[119] = "obj_air_bubble";
global.__objectNames[120] = "obj_water_countdown";
global.__objectNames[121] = "obj_casino_bumper";
global.__objectNames[122] = "obj_moving_handle_up";
global.__objectNames[123] = "obj_moving_handle_down";
global.__objectNames[124] = "obj_moving_handle_right";
global.__objectNames[125] = "obj_moving_handle_left";
global.__objectNames[126] = "obj_marble_swing";
global.__objectNames[127] = "obj_dialogue_box";
global.__objectNames[128] = "par_hang";
global.__objectNames[129] = "obj_hang_test";
global.__objectNames[130] = "obj_sth3_switch";
global.__objectNames[131] = "obj_chaos_emeralds";
global.__objectNames[132] = "obj_zne_test_1";
global.__objectNames[133] = "obj_zne_test_1_pla";
global.__objectNames[134] = "obj_zne_test_2";
global.__objectNames[135] = "obj_zne_test_3";
global.__objectNames[136] = "obj_zne_test_4";
global.__objectNames[137] = "obj_zne_test_5";
global.__objectNames[138] = "obj_zne_test_6";
global.__objectNames[139] = "obj_zne_test_7";
global.__objectNames[140] = "obj_zne_test_8";
global.__objectNames[141] = "obj_zne_test_9";
global.__objectNames[142] = "obj_zne_test_10";
global.__objectNames[143] = "obj_zne_test_11";
global.__objectNames[144] = "obj_zne_test_12";
global.__objectNames[145] = "obj_zne_test_13";
global.__objectNames[146] = "obj_zne_test_14";
global.__objectNames[147] = "obj_zne_test_15";
global.__objectNames[148] = "obj_zne_test_16";
global.__objectNames[149] = "obj_zne_test_17";
global.__objectNames[150] = "obj_zne_test_18";
global.__objectNames[151] = "obj_zne_test_loop_high";
global.__objectNames[152] = "obj_zne_test_loop_solid";
global.__objectNames[153] = "obj_zne_test_loop_low";
global.__objectNames[154] = "obj_zne_test_tunnel";
global.__objectNames[155] = "obj_zne_test_moving_platform";
global.__objectNames[156] = "obj_zne_test_moving_creator";
global.__objectNames[157] = "obj_zne_test_debug";
global.__objectNames[158] = "obj_zne_test_settime";
global.__objectNames[159] = "obj_zne_test_collapse";
global.__objectNames[160] = "obj_zne_test_collapse_pieces";
global.__objectNames[161] = "obj_sky_collapse";
global.__objectNames[162] = "obj_sky_collapse_pieces";
global.__objectNames[163] = "objGHZBG";
global.__objectNames[164] = "obj_bonus_gumball_machine";
global.__objectNames[165] = "obj_bonus_gumball_tiles";
global.__objectNames[166] = "obj_bonus_gumball_rod";
global.__objectNames[167] = "obj_bonus_gumball_plate";
global.__objectNames[168] = "obj_bonus_gumball_bumper";
global.__objectNames[169] = "obj_bonus_gumball_collapse";
global.__objectNames[170] = "obj_bonus_gumball_collapse_pieces";
global.__objectNames[171] = "obj_bonus_gumball_spring_breaker";
global.__objectNames[172] = "obj_bonus_gumball_background";
global.__objectNames[173] = "obj_bonus_gumball";
global.__objectNames[174] = "par_fade";
global.__objectNames[175] = "obj_fade_next";
global.__objectNames[176] = "obj_fade_bonus";
global.__objectNames[177] = "obj_fade_from_bonus";
global.__objectNames[178] = "obj_fade_restart";
global.__objectNames[179] = "obj_fade_game_restart";
global.__objectNames[180] = "obj_fade_end";
global.__objectNames[181] = "obj_fade_super";
global.__objectNames[182] = "obj_fade_to_normal";
global.__objectNames[183] = "obj_collision_terrain01";
global.__objectNames[184] = "obj_collision_terrain02";
global.__objectNames[185] = "obj_collision_terrain03";
global.__objectNames[186] = "obj_collision_terrain04";
global.__objectNames[187] = "obj_collision_terrain05";
global.__objectNames[188] = "obj_collision_terrain06";
global.__objectNames[189] = "obj_collision_terrain07";
global.__objectNames[190] = "obj_collision_terrain08";
global.__objectNames[191] = "obj_collision_terrain09";
global.__objectNames[192] = "obj_collision_terrain10";
global.__objectNames[193] = "obj_collision_terrain11";
global.__objectNames[194] = "obj_collision_terrain12";
global.__objectNames[195] = "obj_collision_terrain13";
global.__objectNames[196] = "obj_collision_terrain14";
global.__objectNames[197] = "obj_collision_terrain15";
global.__objectNames[198] = "obj_collision_terrain16";
global.__objectNames[199] = "obj_collision_terrain17";
global.__objectNames[200] = "obj_collision_terrain18";
global.__objectNames[201] = "obj_collision_terrain19";
global.__objectNames[202] = "obj_collision_terrain20";
global.__objectNames[203] = "obj_collision_terrain21";
global.__objectNames[204] = "obj_collision_terrain22";
global.__objectNames[205] = "obj_collision_terrain23";
global.__objectNames[206] = "obj_collision_terrain_layer_0_01";
global.__objectNames[207] = "obj_collision_terrain_layer_0_02";
global.__objectNames[208] = "obj_collision_terrain_layer_0_03";
global.__objectNames[209] = "obj_collision_terrain_layer_0_04";
global.__objectNames[210] = "obj_collision_terrain_layer_0_05";
global.__objectNames[211] = "obj_collision_terrain_layer_0_06";
global.__objectNames[212] = "obj_collision_terrain_layer_0_07";
global.__objectNames[213] = "obj_collision_terrain_layer_0_08";
global.__objectNames[214] = "obj_collision_terrain_layer_0_09";
global.__objectNames[215] = "obj_collision_terrain_layer_0_10";
global.__objectNames[216] = "obj_collision_terrain_layer_0_11";
global.__objectNames[217] = "obj_collision_terrain_layer_0_12";
global.__objectNames[218] = "obj_collision_terrain_layer_0_13";
global.__objectNames[219] = "obj_collision_terrain_layer_0_14";
global.__objectNames[220] = "obj_collision_terrain_layer_0_15";
global.__objectNames[221] = "obj_collision_terrain_layer_0_16";
global.__objectNames[222] = "obj_collision_terrain_layer_0_17";
global.__objectNames[223] = "obj_collision_terrain_layer_0_18";
global.__objectNames[224] = "obj_collision_terrain_layer_0_19";
global.__objectNames[225] = "obj_collision_terrain_layer_0_20";
global.__objectNames[226] = "obj_collision_terrain_layer_0_21";
global.__objectNames[227] = "obj_collision_terrain_layer_0_22";
global.__objectNames[228] = "obj_collision_terrain_layer_0_23";
global.__objectNames[229] = "obj_collision_terrain_layer_1_01";
global.__objectNames[230] = "obj_collision_terrain_layer_1_02";
global.__objectNames[231] = "obj_collision_terrain_layer_1_03";
global.__objectNames[232] = "obj_collision_terrain_layer_1_04";
global.__objectNames[233] = "obj_collision_terrain_layer_1_05";
global.__objectNames[234] = "obj_collision_terrain_layer_1_06";
global.__objectNames[235] = "obj_collision_terrain_layer_1_07";
global.__objectNames[236] = "obj_collision_terrain_layer_1_08";
global.__objectNames[237] = "obj_collision_terrain_layer_1_09";
global.__objectNames[238] = "obj_collision_terrain_layer_1_10";
global.__objectNames[239] = "obj_collision_terrain_layer_1_11";
global.__objectNames[240] = "obj_collision_terrain_layer_1_12";
global.__objectNames[241] = "obj_collision_terrain_layer_1_13";
global.__objectNames[242] = "obj_collision_terrain_layer_1_14";
global.__objectNames[243] = "obj_collision_terrain_layer_1_15";
global.__objectNames[244] = "obj_collision_terrain_layer_1_16";
global.__objectNames[245] = "obj_collision_terrain_layer_1_17";
global.__objectNames[246] = "obj_collision_terrain_layer_1_18";
global.__objectNames[247] = "obj_collision_terrain_layer_1_19";
global.__objectNames[248] = "obj_collision_terrain_layer_1_20";
global.__objectNames[249] = "obj_collision_terrain_layer_1_21";
global.__objectNames[250] = "obj_collision_terrain_layer_1_22";
global.__objectNames[251] = "obj_collision_terrain_layer_1_23";
global.__objectNames[252] = "obj_collision_terrain_platform_01";
global.__objectNames[253] = "obj_collision_terrain_platform_02";
global.__objectNames[254] = "obj_collision_terrain_platform_03";
global.__objectNames[255] = "obj_collision_terrain_platform_04";
global.__objectNames[256] = "obj_collision_terrain_platform_05";
global.__objectNames[257] = "obj_collision_terrain_platform_06";
global.__objectNames[258] = "obj_collision_terrain_platform_07";
global.__objectNames[259] = "obj_collision_terrain_platform_08";
global.__objectNames[260] = "obj_collision_terrain_platform_09";
global.__objectNames[261] = "obj_collision_terrain_platform_10";
global.__objectNames[262] = "obj_collision_terrain_platform_11";
global.__objectNames[263] = "obj_collision_terrain_platform_12";
global.__objectNames[264] = "obj_collision_terrain_platform_13";
global.__objectNames[265] = "obj_collision_terrain_platform_14";
global.__objectNames[266] = "obj_collision_terrain_platform_15";
global.__objectNames[267] = "obj_collision_terrain_platform_16";
global.__objectNames[268] = "obj_collision_terrain_platform_17";
global.__objectNames[269] = "obj_collision_terrain_platform_18";
global.__objectNames[270] = "obj_collision_terrain_platform_19";
global.__objectNames[271] = "obj_collision_terrain_platform_20";
global.__objectNames[272] = "obj_collision_terrain_platform_21";
global.__objectNames[273] = "obj_collision_terrain_platform_22";
global.__objectNames[274] = "obj_collision_terrain_platform_23";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for