#macro GameTitle "Flicky Engine"
#macro ActionNormal 0
#macro ActionJump 1
#macro ActionCrouch 2
#macro ActionLookup 3
#macro ActionSpindash 4
#macro ActionRolling 5
#macro ActionSkid 6
#macro ActionPush 7
#macro ActionHurt 8
#macro ActionDie 9
#macro ActionFly 10
#macro ActionFlydrop 11
#macro ActionGlide 12
#macro ActionGlidedrop 13
#macro ActionSlide 14
#macro ActionClimb 15
#macro ActionHang 16
#macro ActionShield 17
#macro ActionSpring 18
#macro ActionPeelout 19
#macro ActionBreath 20
#macro ActionTransform 21
#macro ActionHammerDrop 22
#macro ActionUncurl 23
#macro ActionSquirrelGlide 24
#macro ActionFan 25
#macro ActionSpin 26
#macro ShieldDefault 0
#macro ShieldFlames 1
#macro ShieldElectricity 2
#macro ShieldBubble 3
#macro CharacterSonic 1
#macro CharacterTails 2
#macro CharacterKnuckles 3
#macro CharacterAmy 4
#macro CharacterMighty 5
#macro CharacterRay 6
#macro CharacterNormal 1
#macro CharacterSuper 2
#macro CharacterHyper 3
#macro IsPlayable 1
#macro IsCPU 2
